name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Execute unit tests
        run: ./gradlew createDebugCoverageReport

      - name: Report Coveralls
        run: ./gradlew coverallsJacoco

