name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Java JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Execute unit tests
        run: ./gradlew createDebugCoverageReport
      - name: Report Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: ./gradlew coverallsJacoco

