name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run tests and generate coverage report
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          ./gradlew clean test jacocoTestReport

          # Check if coverage report exists and print its content
          if [ -f "build/reports/jacoco/test/jacocoTestReport.xml" ]; then
            cat build/reports/jacoco/test/jacocoTestReport.xml
          else
            echo "Coverage report not found."
          fi

      - name: Upload coverage to Coveralls
        run: |
          ./gradlew coverallsJacoco
